### ISSUE TITLE
It is not possible to disable monitoring

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/component-backup-k8up#12]
## Steps to Reproduce the Problem

  1. Cluster without a push gateway available
  1.
     ```yaml
     parameters:
       backup_k8up:
         prometheus_push_gateway: ''
         monitoring_enabled: false
     ```

## Actual Behavior
Wrestic compains about push gateway not accessible

```
E1016 11:15:32.306402       1 backup.go:145] wrestic "msg"="prometheus send failed" "error"="Post \"http://127.0.0.1/metrics/job/restic_backup/instance/syn-cluster-backup\": dial tcp 127.0.0.1:80: connect: connection refused"  
```

## Expected Behavior
Wrestic does not complain about missing push gateway.
