### ISSUE TITLE
Refactor alert filtering configuration

### ISSUE THREAD

**Issue by simu** [projectsyn/component-backup-k8up#7]
## Context

The current format of the configuration is the following 

```
parameters:
  backup_k8up:
    alert_rule_filters:
      namespace: namespace=~"syn.*"
```

However, while the key in `alert_rule_filters` is called `namespace`, nothing stops users from using different labels to filter alerts.

## Proposal

This issue proposes an alternative structure for the field `parameters.backup_k8up.alert_rule_filters` with the following properties:
1. Keys in `alert_rule_filters` are used to indicate the metric label on which to apply the filter
1. Each key in `alert_rule_filters` holds a dict with one or more of the keys `match`, `match_re`, `exclude` and `exclude_re`.
1. The match/exclude keys are mapped to filtering operations `=`, `=~`, `!=`, and `!~` respectively
1. The value of each of the match/exclude keys is used as the value for the corresponding expression and wrapped in double quotes.

An example might look as follows:

```
parameters:
  backup_k8up:
    alert_rule_filters:
      namespace: 
        match_re: "syn.*"
        exclude_re: ".*(demo|dev).*"
```

## Alternatives

We could go with an array-based approach, but removing array elements in a reclass hierarchy is much trickier than overwriting dict keys.
